import { Link, LinkProps } from 'react-router-dom';
import { styled } from '@mui/material';
export type TLinkProps = Omit<LinkProps,'to'>& {
  href: LinkProps["to"];
  textalign?: string;
  fontSize?: number;
  fontWeight?: number;
  lineheight?: number;
  margin?: string | number;
  padding?: string | number;
  margintop?: number;
  marginbottom?: number;
  paddingTop?: number;
  paddingBottom?: number;
  marginLeft?: number;
  marginright?: number;
  paddingleft?: number;
  paddingright?: number;
  width?: number | string;
  minwidth?: number;
  height?: number | string;
  minHeight?: number;
  uppercase?: boolean;
  color?: string;
  textDecoration?: string;
  underline?: "none" | "hover" | "always";
};

export const StyledLink = styled(Link)<{
  textalign?: string;
  fontSize?: number;
  fontWeight?: number;
  lineheight?: number;
  margin?: string | number;
  padding?: string | number;
  margintop?: number;
  marginbottom?: number;
  paddingTop?: number;
  paddingBottom?: number;
  marginLeft?: number;
  marginright?: number;
  paddingleft?: number;
  paddingright?: number;
  width?: number | string;
  minwidth?: number;
  height?: number | string;
  minHeight?: number;
  uppercase?: boolean;
  color?: string;
  textDecoration?: string;
}>`
  width: ${({ width, theme }) => width && (typeof width === 'string' ? width : theme.spacing(width))};
  height: ${({ height, theme }) => height && (typeof height === 'string' ? height : theme.spacing(height))};
  min-width: ${({ minwidth, theme }) => minwidth && theme.spacing(minwidth)};
  min-height: ${({ minHeight, theme }) => minHeight && theme.spacing(minHeight)};
  text-transform: ${({ uppercase }) => (uppercase ? 'uppercase' : 'none')};
  margin: ${({ margin, theme }) => (margin && Number(margin) ? theme.spacing(margin as number) : margin)};
  padding: ${({ padding, theme }) => (padding && Number(padding) ? theme.spacing(padding as number) : padding)};
  margin-top: ${({ margintop, theme }) => margintop && theme.spacing(margintop)};
  margin-bottom: ${({ marginbottom, theme }) => marginbottom && theme.spacing(marginbottom)};
  padding-top: ${({ paddingTop, theme }) => paddingTop && theme.spacing(paddingTop)};
  padding-bottom: ${({ paddingBottom, theme }) => paddingBottom && theme.spacing(paddingBottom)};
  margin-left: ${({ marginLeft, theme }) => marginLeft && theme.spacing(marginLeft)};
  margin-right: ${({ marginright, theme }) => marginright && theme.spacing(marginright)};
  padding-left: ${({ paddingleft, theme }) => paddingleft && theme.spacing(paddingleft)};
  padding-right: ${({ paddingright, theme }) => paddingright && theme.spacing(paddingright)};
  text-align: ${({ textalign }) => textalign};
  font-size: ${({ fontSize, theme }) => fontSize && theme.spacing(fontSize)};
  font-weight: ${({ fontWeight, theme }) => fontWeight && theme.typography.fontWeightBold};
  line-height: ${({ lineheight, theme }) => lineheight && theme.spacing(lineheight)};
  color: ${({ color }) => color};
  text-decoration: ${({ textDecoration }) => textDecoration || 'none'};
`;
